import React from 'react';
import { Time, TimeC, TimeR } from './Styles';

export const Slot = () => (
  <Time>
    <TimeC>
      <TimeR>09:00</TimeR>
      <TimeR>10:00</TimeR>
    </TimeC>
    <TimeC>
      <TimeR>10:00</TimeR>
      <TimeR>11:00</TimeR>
    </TimeC>
    <TimeC>
      <TimeR>11:00</TimeR>
      <TimeR>12:00</TimeR>
    </TimeC>
    <TimeC>
      <TimeR>12:00</TimeR>
      <TimeR>01:00</TimeR>
    </TimeC>
    <TimeC>
      <TimeR>01:00</TimeR>
      <TimeR>02:00</TimeR>
    </TimeC>
    <TimeC>
      <TimeR>02:00</TimeR>
      <TimeR>03:00</TimeR>
    </TimeC>
    <TimeC>
      <TimeR>03:00</TimeR>
      <TimeR>04:00</TimeR>
    </TimeC>
    <TimeC>
      <TimeR>04:00</TimeR>
      <TimeR>05:00</TimeR>
    </TimeC>
    <TimeC>
      <TimeR>05:00</TimeR>
      <TimeR>06:00</TimeR>
    </TimeC>
    <TimeC>
      <TimeR>06:00</TimeR>
      <TimeR>07:00</TimeR>
    </TimeC>
    <TimeC>
      <TimeR>07:00</TimeR>
      <TimeR>08:00</TimeR>
    </TimeC>
    <TimeC>
      <TimeR>08:00</TimeR>
      <TimeR>09:00</TimeR>
    </TimeC>
    <TimeC>
      <TimeR>09:00</TimeR>
      <TimeR>10:00</TimeR>
    </TimeC>
    <TimeC>
      <TimeR>10:00</TimeR>
      <TimeR>11:00</TimeR>
    </TimeC>
    <TimeC>
      <TimeR>11:00</TimeR>
      <TimeR>12:00</TimeR>
    </TimeC>
  </Time>
);
