export default {
  title: 'Prizes',
  prizeData: [
    {
      id: '1',
      cash: '25k',
      swags: 'swags',
      merchandise: 'official merchandise',
      src: 'https://res.cloudinary.com/dkpdi1wek/image/upload/v1698839425/gold_zvb6fu.png',
      alt: 'Gold Prize Image',
      prizeValue: '25k',
      prizeShadowColor: 'var(--color-primary-green)',
    },
    {
      id: '2',
      cash: '15k',
      swags: 'swags',
      merchandise: 'official merchandise',
      src: 'https://res.cloudinary.com/dkpdi1wek/image/upload/v1698839425/silver_ramqno.png',
      alt: 'Silver Prize Image',
      prizeValue: '15k',
      prizeShadowColor: 'var(--color-primary-blue)',
    },
    {
      id: '3',
      cash: '10k',
      swags: 'swags',
      merchandise: 'official merchandise',
      src: 'https://res.cloudinary.com/dkpdi1wek/image/upload/v1698839425/bronze_vlzvme.png',
      alt: 'Bronze Prize Image',
      prizeValue: '10k',
      prizeShadowColor: 'var(--color-primary-purple)',
    },
  ],
};
