/* eslint-disable max-len */
export default {
  title: 'Meet our Speakers',
  content:
    'We have prepared a list of simple steps one needs to follow to become a true hacker. The person who attains all these abilities will yield the power to hack anything.',
  speakers: [
    {
      id: 'speaker-0',
      name: 'Shantanu Shubham',
      designation: 'SDE @Schlumberger',
      content: 'Roadmap To Competitive Programming & Career Guidance',
      alt: 'speaker: Shantanu Shubham',
      img: {
        src: 'https://res.cloudinary.com/riteshsp2000/image/upload/project-oregano/speakers/1620977022846_bvc0ij.jpg',
        width: '100%',
        height: '100%',
      },
      date: '28th Oct 2021',
      time: '7:00pm IST',
    },
    {
      id: 'speaker-1',
      name: 'Mehul Mohan',
      designation: 'Founder @Codedamn',
      content: 'Deep Dive into how Web works',
      alt: 'speaker: Mehul Mohan',
      img: {
        src: 'https://res.cloudinary.com/riteshsp2000/image/upload/project-oregano/speakers/1_poDssxSNV7AnDTAkUU5qeQ_1_bv66vw.png',
        width: '100%',
        height: '100%',
      },
      date: '28th Oct 2021',
      time: '8:00pm IST',
    },
    {
      id: 'speaker-2',
      name: 'Rishi Raj Jain',
      designation: 'Solutions Engineer @Limelight Networks',
      content: 'Build Your Personal Blog With Next.js, Storyblok, & Layer0',
      alt: 'speaker: Rishi Raj Jain',
      img: {
        src: 'https://res.cloudinary.com/riteshsp2000/image/upload/project-oregano/speakers/p12DEFkn_400x400_nuxknv.jpg',
        width: '100%',
        height: '100%',
      },
      date: '29th Oct 2021',
      time: '11:00am IST',
    },
    {
      id: 'speaker-3',
      name: 'Suhas Motwani',
      designation: '@PepsiCo',
      content: 'Introduction to the world of Product Management',
      alt: 'speaker: Suhas Motwani',
      img: {
        src: 'https://res.cloudinary.com/riteshsp2000/image/upload/project-oregano/speakers/1545987875194_1_orfq4n.png',
        width: '100%',
        height: '100%',
      },
      date: '29th Oct 2021',
      time: '4:00pm IST',
    },
    {
      id: 'speaker-4',
      name: 'Smarth Vasdev',
      designation: 'Growth PM @PeopleGrove',
      content: 'Introduction to the world of Product Management',
      alt: 'speaker: Smarth Vasdev',
      img: {
        src: 'https://res.cloudinary.com/riteshsp2000/image/upload/project-oregano/speakers/s-4_owwsbg.png',
        width: '100%',
        height: '100%',
      },
      date: '29th Oct 2021',
      time: '4:00pm IST',
    },
    {
      id: 'speaker-5',
      name: 'Abel Mathew',
      designation: 'Google Cloud Innovators Champion',
      content: 'Making a career out of hackathons',
      alt: 'speaker: Abel Mathew',
      img: {
        src: 'https://res.cloudinary.com/riteshsp2000/image/upload/v1634794674/project-oregano/speakers/s-5_p3tblx.png',
        width: '100%',
        height: '100%',
      },
      date: '29th Oct 2021',
      time: '6:00pm IST',
    },
    {
      id: 'speaker-6',
      name: 'Shaswat Lenka',
      designation: 'Opencode NITR',
      content: 'Making a career out of hackathons',
      alt: 'speaker: Shaswat Lenka',
      img: {
        src: 'https://res.cloudinary.com/riteshsp2000/image/upload/project-oregano/speakers/s-6_osfdpw.png',
        width: '100%',
        height: '100%',
      },
      date: '29th Oct 2021',
      time: '6:00pm IST',
    },
    {
      id: 'speaker-7',
      name: 'Ayush Bajpai',
      designation: 'Graphics Designer @Starlax Aerospace',
      content: 'Consequences of UI/UX in our decisions',
      alt: 'speaker: Ayush Bajpai',
      img: {
        src: 'https://res.cloudinary.com/riteshsp2000/image/upload/project-oregano/speakers/s-7_box7lm.png',
        width: '100%',
        height: '100%',
      },
      date: '29th Oct 2021',
      time: '9:00pm IST',
    },
    {
      id: 'speaker-8',
      name: 'Rakshaa Viswanathan',
      designation: 'Incoming SDE @Microsoft',
      content: 'Basic Concepts of Machine Learning',
      alt: 'speaker: Rakshaa Viswanathan',
      img: {
        src: 'https://res.cloudinary.com/riteshsp2000/image/upload/v1634794655/project-oregano/speakers/s-8_zhj56p.png',
        width: '100%',
        height: '100%',
      },
      date: '30th Oct 2021',
      time: '9:00am IST',
    },

    {
      id: 'speaker-8.1',
      name: 'Anush Krishna V',
      designation: 'Auth0 Ambassador',
      content: 'Auth0 API Demo',
      alt: 'speaker: Anush Krishna V',
      img: {
        src: 'https://res.cloudinary.com/riteshsp2000/image/upload/project-oregano/speakers/54374648_mq7qmd.png',
        width: '100%',
        height: '100%',
      },
      date: '30th Oct 2021',
      time: '10:30am IST',
    },
    {
      id: 'speaker-8.2',
      name: 'Michael Ido',
      designation: 'Co-Founder Ploomber',
      content: 'ML pipelines in under 30 minutes with Ploomber',
      alt: 'speaker: Michael Ido',
      img: {
        src: 'https://res.cloudinary.com/riteshsp2000/image/upload/project-oregano/speakers/20210731_160851_1_1_rwzpgk.jpg',
        width: '100%',
        height: '100%',
      },
      date: '30th Oct 2021',
      time: '5:00pm IST',
    },
    {
      id: 'speaker-8.3',
      name: 'Eduardo Blancas',
      designation: 'Co-Founder Ploomber',
      content: 'ML pipelines in under 30 minutes with Ploomber',
      alt: 'speaker: Eduardo Blancas',
      img: {
        src: 'https://res.cloudinary.com/riteshsp2000/image/upload/project-oregano/speakers/1567475375315_run4yu.jpg',
        width: '100%',
        height: '100%',
      },
      date: '30th Oct 2021',
      time: '5:00pm IST',
    },
    {
      id: 'speaker-9',
      name: 'Abhishek Chandrasenan',
      designation: 'Full Stack Developer @SAWO Labs',
      content: 'Getting Started with SAWO SDK.',
      alt: 'speaker: Abhishek Chandrasenan',
      img: {
        src: 'https://res.cloudinary.com/riteshsp2000/image/upload/v1634794646/project-oregano/speakers/s-9_y8oubi.png',
        width: '100%',
        height: '100%',
      },
      date: '30th Oct 2021',
      time: '12:00pm IST',
    },
    {
      id: 'speaker-10',
      name: 'Roshni Biswas',
      designation: 'SE @Knowledge Systems',
      content: 'Solving Deep Tech Problems with Open Source',
      alt: 'speaker: Roshni Biswas',
      img: {
        src: 'https://res.cloudinary.com/riteshsp2000/image/upload/project-oregano/speakers/s-10_vlorjg.png',
        width: '100%',
        height: '100%',
      },
      date: '30th Oct 2021',
      time: '7:00pm IST',
    },
    {
      id: 'speaker-11',
      name: 'Anurag Saha Roy',
      designation: 'Co-Founder of Wikilimo',
      content: 'Solving Deep Tech Problems with Open Source',
      alt: 'speaker: Anurag Saha Roy',
      img: {
        src: 'https://res.cloudinary.com/riteshsp2000/image/upload/project-oregano/speakers/s-11_nhjevy.png',
        width: '100%',
        height: '100%',
      },
      date: '30th Oct 2021',
      time: '7:00pm IST',
    },
  ],
};
