export default {
  alpha: [
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1698845838/ey8cgmpazpevz909blic.png',
      name: 'Devfolio',
      link: 'https://devfolio.co/',
      alt: 'Devfolio',
    },
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1698861840/MLH_kl7xle.png',
      name: 'Major League Hacking',
      link: 'https://mlh.io/',
      alt: 'Major League Hacking',
    },
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1698861840/Polygon_klk8a1.png',
      name: 'Polygon',
      link: 'https://polygon.technology/',
      alt: 'Polygon',
    },
  ],
  beta: [
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1698861840/Quine_efnzpr.png',
      name: 'Quine',
      link: 'https://quine.sh/',
      alt: 'Quine',
    },
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1698861844/Solana_nl1837.png',
      name: 'Solana',
      link: 'https://solana.com',
      alt: 'Solana',
    },
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1698861839/Filecoin_cf3ncu.png',
      name: 'Filecoin',
      link: 'https://filecoin.io',
      alt: 'Filecoin',
    },
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1698861843/Replit_ihsdqh.png',
      name: 'Replit',
      link: 'https://replit.com',
      alt: 'Replit',
    },
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1698861843/Shardeum_caarst.png',
      name: 'Shardeum',
      link: 'https://shardeum.org/',
      alt: 'Shardeum',
    },
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1698861839/DigitalOcean_dno5fq.png',
      name: 'Digitalocean',
      link: 'https://digitalocean.com/',
      alt: 'Digitalocean',
    },
  ],
  gamma: [
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1698861839/Apyhub_tnqfbm.png',
      name: 'Apyhub',
      link: 'https://apyhub.com/',
      alt: 'Apyhub',
    },
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1698861902/z4wcjva6lqs63qbleyis.png',
      name: 'LIFI',
      link: 'https://li.fi/',
      alt: 'LIFI',
    },
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1698861902/wqovjcdfooqxabbfatrx.png',
      name: 'Earthhacks',
      link: 'https://earthhacks.io/',
      alt: 'Earthhacks',
    },
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1698861844/Tezos_wiih64.png',
      name: 'Tezos',
      link: 'https://tezos.com/',
      alt: 'Tezos',
    },
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1698861901/hcixunszfysezhmz9xwc.png',
      name: 'Buidlerstribe',
      link: 'https://buidlerstribe.com/',
      alt: 'Buidlerstribe',
    },
  ],
  deltaFirst: [
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1698861840/MLH_kl7xle.png',
      name: 'Major League Hacking',
      link: 'https://mlh.io/',
      alt: 'Major League Hacking',
      width: '42%',
    },
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1698861840/Polygon_klk8a1.png',
      name: 'Polygon',
      link: 'https://polygon.technology/',
      alt: 'Polygon',
      width: '42%',
    },
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1699283820/Wolfram_Logo_tzkyao.png',
      name: 'Wolfram',
      link: 'https://www.wolfram.com/',
      alt: 'Wolfram',
      width: '42%',
    },
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1698861844/Twilio_cq7m3h.png',
      name: 'Twilio',
      link: 'https://www.twilio.com/',
      alt: 'Twilio',
      width: '42%',
    },
  ],
  deltaSecond: [
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1698861902/a25k67wos9exof9hxxfm.png',
      name: 'Echo3d',
      link: 'https://www.echo3d.com/',
      alt: 'Echo3d',
      width: '542%',
    },
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1698861847/Velo_v20ync.png',
      name: 'Velo',
      link: 'https://www.wix.com/velo',
      alt: 'Velo',
      width: '542%',
    },
    {
      src: 'https://res.cloudinary.com/dv1src8un/image/upload/v1698861847/Xyz_tyhkq9.png',
      name: 'xyz',
      link: 'https://gen.xyz/',
      alt: 'xyz',
      width: '542%',
    },
  ],
};
