/* eslint-disable max-len */
export default {
  id: 'sponsors',
  title: 'Our Awesome Sponsors',
  content:
    'Our love for open source and drive to make an impact materialized as HackNITR 4.0. Backed by likes of participating students, we grew steadily to organize hackathons and support social initiatives. Today,we bring you the opportunity to collaborate with us on our next endeavour.',
  alpha: [
    {
      src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/past_rv4xvj.png',
      name: 'Devfolio',
      size: '90%',
      link: 'https://devfolio.co/',
      width: '150px',
      alt: 'Devfolio',
    },
    {
      src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/MLH_xejp6v.png',
      name: 'Major League Hacking',
      size: '90%',
      link: 'https://mlh.io/',
      width: '170px',
      alt: 'Major League Hacking',
    },
    {
      src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/polygon_vvmhvg.png',
      name: 'Polygon',
      size: '90%',
      link: 'https://polygon.technology/',
      width: '180px',
      alt: 'Polygon',
    },
  ],
  beta: [
    {
      src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1672153500/Sponsors/white_e5gwsk.svg',
      name: 'Quine',
      size: '90%',
      link: 'https://quine.sh/',
      width: '170px',
      alt: 'Quine',
    },
    {
      src: 'https://res.cloudinary.com/ratnakar5938/image/upload/v1667587758/hn/Solana_Dark_wmguj1.svg',
      name: 'Solana',
      size: '90%',
      link: 'https://solana.com',
      width: '170px',
      alt: 'Solana',
    },
    {
      src: 'https://res.cloudinary.com/ratnakar5938/image/upload/v1667588043/hn/Filecoin_Coloured_White_Text-1_q7q08w.png',
      name: 'Filecoin',
      size: '90%',
      link: 'https://filecoin.io',
      width: '170px',
      alt: 'Filecoin',
    },
    {
      src: 'https://res.cloudinary.com/ratnakar5938/image/upload/v1667588167/hn/replit_fpppab.svg',
      name: 'Replit',
      size: '90%',
      link: 'https://replit.com',
      width: '170px',
      alt: 'Replit',
    },
    {
      src: 'https://res.cloudinary.com/dujqfyato/image/upload/v1673028465/HackNITR/Shardeum_Logo_Light_thajcd_zsfpax.svg',
      name: 'shardeum',
      size: '90%',
      link: 'https://shardeum.org/',
      width: '170px',
      alt: 'shardeum',
    },
    {
      src: 'https://assets.devfolio.co/hackathons/63b3a379347c43328212ef6618c1aaa3/sponsors/71d81da18cfa4892a24f0cb7d9b0ea18/854.png',
      name: 'digitalocean',
      size: '90%',
      link: 'https://digitalocean.com/',
      width: '170px',
      alt: 'digitalocean',
    },
  ],
  gamma: [
    {
      src: 'https://res.cloudinary.com/dujqfyato/image/upload/v1673027909/HackNITR/apyhub-logo-negative-tm_hncnyj_m2segf.svg',
      name: 'Apyhub',
      size: '100%',
      link: 'https://apyhub.com/',
      alt: 'Apyhub',
    },
    {
      src: 'https://assets.devfolio.co/hackathons/63b3a379347c43328212ef6618c1aaa3/sponsors/2989606dfb894c4b8df46a5e7f71a24f/202.jpeg',
      name: 'Tezos',
      size: '100%',
      link: 'https://tezos.com/',
      alt: 'Tezos',
    },
    {
      src: 'https://res.cloudinary.com/dujqfyato/image/upload/v1673027915/HackNITR/logo_lifi_horizontal_dark_theme_efwedc_muzkpc.svg',
      name: 'LIFI',
      size: '100%',
      link: 'https://li.fi/',
      alt: 'LIFI',
    },
    {
      src: 'https://res.cloudinary.com/dujqfyato/image/upload/v1673027910/HackNITR/download_6_ooswsx_d9idrb.png',
      name: 'earthhacks',
      size: '100%',
      link: 'https://earthhacks.io/',
      alt: 'earthhacks',
    },
    {
      src: 'https://res.cloudinary.com/dujqfyato/image/upload/v1673792160/HackNITR/BuidlersTribe-Logo-White_w0hh5f.png',
      name: 'buidlerstribe',
      size: '100%',
      link: 'https://buidlerstribe.com/',
      alt: 'buidlerstribe',
    },
  ],
  delta: [
    {
      src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1671869547/Sponsors/StreamYard_-_Horz_2_kisme6.png',
      name: 'StreamYard',
      size: '100%',
      link: 'https://streamyard.com/',
      alt: 'StreamYard',
    },
    {
      src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1671869548/Sponsors/Voiceflow_Logo_White_pre3ml.png',
      name: 'Voiceflow',
      size: '100%',
      link: 'https://www.voiceflow.com/',
      alt: 'Voiceflow',
    },
    {
      src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/wolfram_sid6kv.png',
      name: 'Wolfram',
      size: '100%',
      link: 'https://www.wolfram.com/',
      alt: 'Wolfram',
    },
    {
      src: 'https://res.cloudinary.com/dujqfyato/image/upload/v1673028465/HackNITR/Screenshot_from_2022-12-27_18-20-16_zuupj6_nu8pzj.png',
      name: 'CockRoachDB',
      size: '11 0%',
      link: 'https://www.cockroachlabs.com/',
      alt: 'CockRoachDB',
    },
    {
      src: 'https://res.cloudinary.com/dujqfyato/image/upload/v1673027913/HackNITR/GoDaddy-White-Logo.wine_w2zbub_gtns7e.svg',
      name: 'GoDaddy',
      size: '100%',
      link: 'https://www.godaddy.com/en-in',
      alt: 'GoDaddy',
    },
    {
      src: 'https://res.cloudinary.com/dujqfyato/image/upload/v1673028465/HackNITR/unnamed_ckyvcj_ur8rue.png',
      name: 'Twilio',
      size: '100%',
      link: 'https://www.twilio.com/',
      alt: 'Twilio',
    },
    {
      src: 'https://res.cloudinary.com/dujqfyato/image/upload/v1673027909/HackNITR/brand_evolution_logo_Auth0_white_m8hcor_rl1thh.svg',
      name: 'auth0',
      size: '100%',
      link: 'https://auth0.com/',
      alt: 'auth0',
    },
    {
      src: 'https://res.cloudinary.com/dujqfyato/image/upload/v1673027910/HackNITR/download_qjusxz_dccnpa.png',
      name: 'velo',
      size: '90%',
      link: 'https://www.wix.com/velo',
      alt: 'velo',
    },
    {
      src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1671868833/Sponsors/white-logo-fueler_k177pt.png',
      name: 'Fueler',
      size: '100%',
      link: 'https://fueler.io/',
      alt: 'Fueler',
    },
    {
      src: 'https://d1yjjnpx0p53s8.cloudfront.net/styles/logo-thumbnail/s3/052019/axure_logo_4001x.png?bkzcT4rEHbOSEpTxkZdEi6G3aoPwy1xH&itok=eVx3xGaP',
      name: 'Axure',
      size: '100%',
      link: 'https://www.axure.com/',
      alt: 'Axure',
    },
    {
      src: 'https://assets.devfolio.co/hackathons/63b3a379347c43328212ef6618c1aaa3/sponsors/efcc5c3e75dd4ce0976f22714a3537c3/141.png',
      name: 'hoverrobotix',
      size: '100%',
      link: 'https://hoverrobotix.com/',
      alt: 'hoverrobotix',
    },
    {
      src: 'https://www.echo3d.com/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fecho3D_logo.b341e4a8.png&w=1080&q=75',
      name: 'echo3d',
      size: '100%',
      link: 'https://www.echo3d.com/',
      alt: 'echo3d',
    },
    {
      src: 'https://assets.devfolio.co/hackathons/63b3a379347c43328212ef6618c1aaa3/sponsors/4b7188f587ce4aefb4857f80ccc4f361/281.jpeg',
      name: 'interviewbuddy',
      size: '100%',
      link: 'https://interviewbuddy.in/',
      alt: 'interviewbuddy',
    },
    {
      src: 'https://res.cloudinary.com/dujqfyato/image/upload/v1673028466/HackNITR/xyz-logo-white_uc8th5_kxldjo.svg',
      name: 'xyz',
      size: '100%',
      link: 'https://gen.xyz/',
      alt: 'xyz',
    },
    {
      src: 'https://onehacks.org/assets/images/Leading_Learners_White_Logo_Full_Text_PNG.png',
      name: 'leadlearners',
      size: '100%',
      link: 'https://www.leadlearners.ca/',
      alt: 'leadlearners',
    },
  ],
};
