/* eslint-disable max-len */
export default {
  id: 'sponsors',
  title: 'Our Awesome Sponsors',
  content:
    'Our love for open source and drive to make an impact materialized as HackNITR 4.0. Backed by likes of participating students, we grew steadily to organize hackathons and support social initiatives. Today,we bring you the opportunity to collaborate with us on our next endeavour.',
  alpha: [
    {
      src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/past_rv4xvj.png',
      name: 'Devfolio',
      size: '90%',
      link: 'https://devfolio.co/',
      width: '150px',
      alt: 'Devfolio',
    },
    {
      src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/MLH_xejp6v.png',
      name: 'Major League Hacking',
      size: '90%',
      link: 'https://mlh.io/',
      width: '170px',
      alt: 'Major League Hacking',
    },
    {
      src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/polygon_vvmhvg.png',
      name: 'Polygon',
      size: '90%',
      link: 'https://polygon.technology/',
      width: '180px',
      alt: 'Polygon',
    },
  ],
  beta: [
    // {
    //   src: 'https://res.cloudinary.com/ratnakar5938/image/upload/v1667587758/hn/Solana_Dark_wmguj1.svg',
    //   name: 'Solana',
    //   size: '65%',
    //   link: 'https://solana.com',
    //   width: '170px',
    //   alt: 'Solana',
    // },
    // {
    //   src: 'https://res.cloudinary.com/ratnakar5938/image/upload/v1667588043/hn/Filecoin_Coloured_White_Text-1_q7q08w.png',
    //   name: 'Filecoin',
    //   size: '65%',
    //   link: 'https://filecoin.io',
    //   width: '170px',
    //   alt: 'Filecoin',
    // },
    {
      src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1672153500/Sponsors/white_e5gwsk.svg',
      name: 'Quine',
      size: '90%',
      link: 'https://quine.sh/',
      width: '170px',
      alt: 'Quine',
    },
    {
      src: 'https://res.cloudinary.com/ratnakar5938/image/upload/v1667587758/hn/Solana_Dark_wmguj1.svg',
      name: 'Solana',
      size: '90%',
      link: 'https://solana.com',
      width: '170px',
      alt: 'Solana',
    },
    {
      src: 'https://res.cloudinary.com/ratnakar5938/image/upload/v1667588043/hn/Filecoin_Coloured_White_Text-1_q7q08w.png',
      name: 'Filecoin',
      size: '90%',
      link: 'https://filecoin.io',
      width: '170px',
      alt: 'Filecoin',
    },
    {
      src: 'https://res.cloudinary.com/ratnakar5938/image/upload/v1667588167/hn/replit_fpppab.svg',
      name: 'Replit',
      size: '90%',
      link: 'https://replit.com',
      width: '170px',
      alt: 'Replit',
    },
  ],
  gamma: [
    {
      src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1672148510/Sponsors/tezos_sfn5do.png',
      name: 'Tezos',
      size: '100%',
      link: 'https://tezos.com/',
      alt: 'Tezos',
    },
    {
      src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1672153097/Sponsors/logo_lifi_horizontal_dark_theme_cf2gbb.svg',
      name: 'Li.fi',
      size: '100%',
      link: 'https://li.fi/',
      alt: 'Li.fi',
    },
    {
      src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1672153785/Sponsors/apyhub-logo-rgb-tm_eqgfcs.svg',
      name: 'Apyhub',
      size: '100%',
      link: 'https://apyhub.com/',
      alt: 'Apyhub',
    },

    //     {
    //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/wolfram_sid6kv.png',
    //       name: 'Wolfram',
    //       size: '100%',
    //       link: 'https://www.wolfram.com/language/',
    //       alt: 'Wolfram',
    //     },
    //     {
    //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/koii_wsget6.png',
    //       name: 'Koii Network',
    //       size: '65%',
    //       link: 'https://koii.network/',
    //       alt: 'Koii Network',
    //     },
  ],
  delta: [
    {
      src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1672148510/Sponsors/twilio_xahhqf.png',
      name: 'Twilio',
      size: '100%',
      link: 'https://www.twilio.com/',
      alt: 'Twilio',
    },
    {
      src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1671869547/Sponsors/StreamYard_-_Horz_2_kisme6.png',
      name: 'StreamYard',
      size: '100%',
      link: 'https://streamyard.com/',
      alt: 'StreamYard',
    },
    // {
    //   src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1672148508/Sponsors/Cockroach_DB_g34nei.png',
    //   name: 'CockroachDB',
    //   size: '100%',
    //   link: 'https://www.cockroachlabs.com/',
    //   alt: 'CockroachDB',
    // },
    {
      src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1671869548/Sponsors/Voiceflow_Logo_White_pre3ml.png',
      name: 'Voiceflow',
      size: '100%',
      link: 'https://www.voiceflow.com/',
      alt: 'Voiceflow',
    },
    {
      src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/wolfram_sid6kv.png',
      name: 'Wolfram',
      size: '100%',
      link: 'https://www.wolfram.com/',
      alt: 'Wolfram',
    },
    // {
    //   src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1672148509/Sponsors/GoDaddy_uhfn0e.png',
    //   name: 'GoDaddy Registry',
    //   size: '100%',
    //   link: 'https://registry.godaddy/',
    //   alt: 'GoDaddy Registry',
    // },
    // {
    //   src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1672148510/Sponsors/auth0_yispya.png',
    //   name: 'Auth0',
    //   size: '100%',
    //   link: 'https://auth0.com/',
    //   alt: 'Auth0',
    // },
    {
      src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1672148509/Sponsors/velo_wsx1yf.png',
      name: 'Wix',
      size: '100%',
      link: 'https://www.wix.com/velo',
      alt: 'Wix',
    },
  ],
};
