
export const sponsors = {
    title: 'Our Awesome Sponsors',
    content:
      'Our love for open source and drive to make an impact materialized as HackNITR 3.0. Backed by likes of participating students, we grew steadily to organize hackathons and support social initiatives. Today,we bring you the opportunity to collaborate with us on our next endeavour.',
    alpha: [
      {
        src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/past_rv4xvj.png',
        name: 'Devfolio',
        size: '95%',
        link: 'https://devfolio.co/',
        width: '170px',
        alt: 'Devfolio',
      },
      {
        src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/past_rv4xvj.png',
        name: 'Devfolio',
        size: '95%',
        link: 'https://devfolio.co/',
        width: '170px',
        alt: 'Devfolio',
      },
      {
        src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/past_rv4xvj.png',
        name: 'Devfolio',
        size: '95%',
        link: 'https://devfolio.co/',
        width: '170px',
        alt: 'Devfolio',
      },
      {
        src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/past_rv4xvj.png',
        name: 'Devfolio',
        size: '95%',
        link: 'https://devfolio.co/',
        width: '170px',
        alt: 'Devfolio',
      },
    ],
    beta: [
      {
        src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/past_rv4xvj.png',
        name: 'Devfolio',
        size: '95%',
        link: 'https://devfolio.co/',
        alt: 'Devfolio',
      },
      {
        src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/past_rv4xvj.png',
        name: 'Devfolio',
        size: '95%',
        link: 'https://devfolio.co/',
        alt: 'Devfolio',
      },
      {
        src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/past_rv4xvj.png',
        name: 'Devfolio',
        size: '95%',
        link: 'https://devfolio.co/',
        alt: 'Devfolio',
      },
      {
        src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/past_rv4xvj.png',
        name: 'Devfolio',
        size: '95%',
        link: 'https://devfolio.co/',
        alt: 'Devfolio',
      },
      {
        src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/past_rv4xvj.png',
        name: 'Devfolio',
        size: '95%',
        link: 'https://devfolio.co/',
        alt: 'Devfolio',
      },
      {
        src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/past_rv4xvj.png',
        name: 'Devfolio',
        size: '95%',
        link: 'https://devfolio.co/',
        alt: 'Devfolio',
      },
      {
        src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/past_rv4xvj.png',
        name: 'Devfolio',
        size: '95%',
        link: 'https://devfolio.co/',
        alt: 'Devfolio',
      },
      {
        src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/past_rv4xvj.png',
        name: 'Devfolio',
        size: '95%',
        link: 'https://devfolio.co/',
        alt: 'Devfolio',
      },
      {
        src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/past_rv4xvj.png',
        name: 'Devfolio',
        size: '95%',
        link: 'https://devfolio.co/',
        alt: 'Devfolio',
      },
      {
        src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/past_rv4xvj.png',
        name: 'Devfolio',
        size: '95%',
        link: 'https://devfolio.co/',
        alt: 'Devfolio',
      },
    ],
  //   gamma: [
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/echoAR_-_Logo_2020_-_Knockout_c9smwf.png',
  //       name: 'EchoAR',
  //       size: '100%',
  //       link: 'https://www.echoar.xyz/',
  //       alt: 'EchoAR',
  //     },
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/lincode_y9pcdh.png',
  //       name: 'Linode',
  //       size: '100%',
  //       link: 'https://www.linode.com/',
  //       alt: 'Linode',
  //     },
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/sticker-mule_j0soly.svg',
  //       name: 'StickerMule',
  //       size: '80%',
  //       link: 'https://www.stickermule.com/',
  //       alt: 'StickerMule',
  //     },
  
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/wolfram_sid6kv.png',
  //       name: 'Wolfram',
  //       size: '100%',
  //       link: 'https://www.wolfram.com/language/',
  //       alt: 'Wolfram',
  //     },
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/koii_wsget6.png',
  //       name: 'Koii Network',
  //       size: '65%',
  //       link: 'https://koii.network/',
  //       alt: 'Koii Network',
  //     },
  //   ],
  //   delta: [
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/Untitled_nqdjaf.png',
  //       name: 'Repl.it',
  //       size: '100%',
  //       link: 'https://replit.com/',
  //       alt: 'Repl.it',
  //     },
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/taskade-circle-logo-full-white_iakfy1.png',
  //       name: 'Taskade',
  //       size: '100%',
  //       link: 'https://www.taskade.com/',
  //       alt: 'Taskade',
  //     },
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/edited_tweetbeam_x3dv1r.png',
  //       name: 'Tweetbeam',
  //       size: '100%',
  //       link: 'https://www.tweetbeam.com/',
  //       alt: 'Tweetbeam',
  //     },
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/Voiceflow_White_iczupf.png',
  //       name: 'Voiceflow',
  //       size: '100%',
  //       link: 'https://www.voiceflow.com/',
  //       alt: 'Voiceflow',
  //     },
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/filterbeans-removebg-preview_jidk5d.png',
  //       name: 'Filter_Beans',
  //       size: '70%',
  //       link: 'https://www.instagram.com/filter_beans/?hl=en',
  //       alt: 'Filter_Beans',
  //     },
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/leadinglearners_vfs68g.png',
  //       name: 'Leading Learners',
  //       size: '55%',
  //       link: 'https://www.leadlearners.ca/',
  //       alt: 'Leading Learners',
  //     },
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/ploomber-removebg-preview_ylm6jf.png',
  //       name: 'Ploomber',
  //       size: '125%',
  //       link: 'https://ploomber.io/',
  //       alt: 'Ploomber',
  //     },
  //   ],
  //   'media-partners': [
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/townscript_pfowad.svg',
  //       name: 'TownScript',
  //       size: '100%',
  //       link: 'https://www.townscript.com/e/hacknitr-30-313200',
  //       alt: 'TownScript',
  //     },
  
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/cross_web1-removebg-preview_q0jxv5.png',
  //       name: 'CrossWeb',
  //       size: '100%',
  //       link: 'https://crossweb.pl/en/events/hacknitr-3-0-pazdziernik-2021/',
  //       alt: 'CrossWeb',
  //     },
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/eventbrite_o4xg44.png',
  //       name: 'EventBrite',
  //       size: '85%',
  //       link: 'https://www.eventbrite.com/e/hacknitr-30-tickets-182495126837',
  //       alt: 'EventBrite',
  //     },
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/nb_cohya7.png',
  //       name: 'Noticebard',
  //       size: '80%',
  //       link: '',
  //       alt: 'Noticebard',
  //     },
      
  //   ],
  //   'authentication-partner': [
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/sawo_ktm83d.png',
  //       name: 'SAWO Labs',
  //       size: '12rem',
  //       link: 'https://sawolabs.com/',
  //       width: '180px',
  //       alt: 'SAWO Labs',
  //       marginTop: '10px',
  //     },
  //   ],
  //   'mental-health-partner': [
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/rahee1_bsa2ir.png',
  //       name: 'Raahee',
  //       size: '8rem',
  //       link: 'https://raahee.in/',
  //       width: '180px',
  //       alt: 'Raahee',
  //       padd: '0',
  //     },
  //   ],
  //   'coding-partner': [
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/v1644908787/hacknitr/sponsors/coding_ninja_lix9vs.png',
  //       name: 'Coding Ninjas',
  //       size: '12rem',
  //       link: 'https://www.codingninjas.com/',
  //       width: '180px',
  //       alt: 'Coding Ninjas',
  //       marginTop: '10px',
  //     },
  //   ],
   };