/* eslint-disable max-len */
export default {
  title: 'Our Awesome Sponsors',
  content:
    'Our love for open source and drive to make an impact materialized as HackNITR 4.0. Backed by likes of participating students, we grew steadily to organize hackathons and support social initiatives. Today,we bring you the opportunity to collaborate with us on our next endeavour.',
  alpha: [
    {
      src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/past_rv4xvj.png',
      name: 'Devfolio',
      size: '90%',
      link: 'https://devfolio.co/',
      width: '150px',
      alt: 'Devfolio',
    },
    {
      src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/MLH_xejp6v.png',
      name: 'Major League Hacking',
      size: '90%',
      link: 'https://mlh.io/',
      width: '170px',
      alt: 'Major League Hacking',
    },
    {
      src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/polygon_vvmhvg.png',
      name: 'Polygon',
      size: '90%',
      link: 'https://polygon.technology/',
      width: '180px',
      alt: 'Polygon',
    },
    // {
    //   src: null,
    //   name: 'Diamond Jubilee',
    //   size: '55%',
    //   link: 'https://www.nitrkl.ac.in/',
    //   width: '100px',
    //   alt: 'Diamond Jubilee',
    // },
    // {
    //   src: 'https://res.cloudinary.com/riteshsp2000/image/upload/project-oregano/sponsors/alpha/ogaeyl6batos4n5cumtz.png',
    //   name: 'Diamond Jubilee',
    //   size: '60%',
    //   link: 'https://www.nitrkl.ac.in/',
    //   width: '100px',
    //   alt: 'Diamond Jubilee',
    // },
  ],
  beta: [
    // {
    //   src: 'https://res.cloudinary.com/ratnakar5938/image/upload/v1667587758/hn/Solana_Dark_wmguj1.svg',
    //   name: 'Solana',
    //   size: '65%',
    //   link: 'https://solana.com',
    //   width: '170px',
    //   alt: 'Solana',
    // },
    // {
    //   src: 'https://res.cloudinary.com/ratnakar5938/image/upload/v1667588043/hn/Filecoin_Coloured_White_Text-1_q7q08w.png',
    //   name: 'Filecoin',
    //   size: '65%',
    //   link: 'https://filecoin.io',
    //   width: '170px',
    //   alt: 'Filecoin',
    // },
    // {
    //   src: 'https://res.cloudinary.com/ratnakar5938/image/upload/v1667588167/hn/replit_fpppab.svg',
    //   name: 'Replit',
    //   size: '65%',
    //   link: 'https://replit.com',
    //   width: '170px',
    //   alt: 'Replit',
    // },
    {
      src: 'https://res.cloudinary.com/ratnakar5938/image/upload/v1667587758/hn/Solana_Dark_wmguj1.svg',
      name: 'Solana',
      size: '90%',
      link: 'https://solana.com',
      width: '170px',
      alt: 'Solana',
    },
    {
      src: 'https://res.cloudinary.com/ratnakar5938/image/upload/v1667588043/hn/Filecoin_Coloured_White_Text-1_q7q08w.png',
      name: 'Filecoin',
      size: '90%',
      link: 'https://filecoin.io',
      width: '170px',
      alt: 'Filecoin',
    },
    {
      src: 'https://res.cloudinary.com/ratnakar5938/image/upload/v1667588167/hn/replit_fpppab.svg',
      name: 'Replit',
      size: '90%',
      link: 'https://replit.com',
      width: '170px',
      alt: 'Replit',
    },
  ],
     gamma:[
       {
          src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1671868833/Sponsors/white-logo-fueler_k177pt.png',
          name: 'Fueler',
          size: '100%',
          link: 'https://fueler.io/',
          alt: 'Fueler',
        },
      {
        src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1671881152/Sponsors/Axure_logo_175_o3d91l.svg',
        name: 'Axure',
        size: '100%',
        link: 'https://www.axure.com/',
        alt: 'Axure',
      },
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/sticker-mule_j0soly.svg',
  //       name: 'StickerMule',
  //       size: '80%',
  //       link: 'https://www.stickermule.com/',
  //       alt: 'StickerMule',
  //     },

  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/wolfram_sid6kv.png',
  //       name: 'Wolfram',
  //       size: '100%',
  //       link: 'https://www.wolfram.com/language/',
  //       alt: 'Wolfram',
  //     },
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/koii_wsget6.png',
  //       name: 'Koii Network',
  //       size: '65%',
  //       link: 'https://koii.network/',
  //       alt: 'Koii Network',
  //     },
     ],
    delta: [
      {
        src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1671869547/Sponsors/StreamYard_-_Horz_2_kisme6.png',
        name: 'StreamYard',
        size: '100%',
        link: 'https://streamyard.com/',
        alt: 'StreamYard',
      },
      {
        src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1671869548/Sponsors/Voiceflow_Logo_White_pre3ml.png',
        name: 'Voiceflow',
        size: '100%',
        link: 'https://www.voiceflow.com/',
        alt: 'Voiceflow',
      },
      // {
      //   src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1671881152/Sponsors/Axure_logo_175_o3d91l.svg',
      //   name: 'Axure',
      //   size: '100%',
      //   link: 'https://www.axure.com/',
      //   alt: 'Axure',
      // },
      {
        src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/wolfram_sid6kv.png',
        name: 'Wolfram',
        size: '100%',
        link: 'https://www.wolfram.com/',
        alt: 'Wolfram',
      },
      // {
      //   src: 'https://res.cloudinary.com/dme9vltjf/image/upload/v1671868833/Sponsors/white-logo-fueler_k177pt.png',
      //   name: 'Fueler',
      //   size: '100%',
      //   link: 'https://fueler.io/',
      //   alt: 'Fueler',
      // },
      // {
      //   src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/leadinglearners_vfs68g.png',
      //   name: 'Leading Learners',
      //   size: '55%',
      //   link: 'https://www.leadlearners.ca/',
      //   alt: 'Leading Learners',
      // },
      // {
      //   src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/ploomber-removebg-preview_ylm6jf.png',
      //   name: 'Ploomber',
      //   size: '125%',
      //   link: 'https://ploomber.io/',
      //   alt: 'Ploomber',
      // },
    ],
  //   'media-partners': [
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/townscript_pfowad.svg',
  //       name: 'TownScript',
  //       size: '100%',
  //       link: 'https://www.townscript.com/e/hacknitr-30-313200',
  //       alt: 'TownScript',
  //     },

  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/cross_web1-removebg-preview_q0jxv5.png',
  //       name: 'CrossWeb',
  //       size: '100%',
  //       link: 'https://crossweb.pl/en/events/hacknitr-3-0-pazdziernik-2021/',
  //       alt: 'CrossWeb',
  //     },
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/eventbrite_o4xg44.png',
  //       name: 'EventBrite',
  //       size: '85%',
  //       link: 'https://www.eventbrite.com/e/hacknitr-30-tickets-182495126837',
  //       alt: 'EventBrite',
  //     },
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/nb_cohya7.png',
  //       name: 'Noticebard',
  //       size: '80%',
  //       link: '',
  //       alt: 'Noticebard',
  //     },

  //   ],
  //   'authentication-partner': [
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/sawo_ktm83d.png',
  //       name: 'SAWO Labs',
  //       size: '12rem',
  //       link: 'https://sawolabs.com/',
  //       width: '180px',
  //       alt: 'SAWO Labs',
  //       marginTop: '10px',
  //     },
  //   ],
  //   'mental-health-partner': [
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/hacknitr/sponsors/rahee1_bsa2ir.png',
  //       name: 'Raahee',
  //       size: '8rem',
  //       link: 'https://raahee.in/',
  //       width: '180px',
  //       alt: 'Raahee',
  //       padd: '0',
  //     },
  //   ],
  //   'coding-partner': [
  //     {
  //       src: 'https://res.cloudinary.com/db4zymomi/image/upload/v1644908787/hacknitr/sponsors/coding_ninja_lix9vs.png',
  //       name: 'Coding Ninjas',
  //       size: '12rem',
  //       link: 'https://www.codingninjas.com/',
  //       width: '180px',
  //       alt: 'Coding Ninjas',
  //       marginTop: '10px',
  //     },
  //   ],
};
