export const timelinecontent = {
  title: 'Timeline',
  nodes: [
    {
      serialid: 1,
      date: '15',
      month: 'October',
      title: 'Registration Opens',
      duration: '15 oct to 15 dec',
      boxcolor: '#72F7BF',
      wheelcolor: '#35E1FF',
      ellipsecolor: '#B067FF',
      ellipsecontent: 'Get extra perks with early registration',
    },
    {
      serialid: 2,
      date: '15',
      month: 'October',
      title: 'Registration Opens',
      duration: '15 oct to 15 dec',
      boxcolor: '#72F7BF',
      wheelcolor: '#35E1FF',
    },
    {
      serialid: 3,
      date: '15',
      month: 'October',
      title: 'Registration Opens',
      duration: '15 oct to 15 dec',
      boxcolor: '#72F7BF',
      wheelcolor: '#35E1FF',
      ellipsecolor: '#B067FF',
      ellipsecontent: 'Get extra perks with early registration',
    },
    {
      serialid: 4,
      date: '15',
      month: 'October',
      title: 'Registration Opens',
      duration: '15 oct to 15 dec',
      boxcolor: '#72F7BF',
      wheelcolor: '#35E1FF',
    },
  ],
};
